const RESTAURANT_ACTION_TYPES = {
    FETCH_RESTAURANT_DATA_START: 'FETCH_RESTAURANT_DATA_START',
    FETCH_RESTAURANT_DATA_SUCCESS: 'FETCH_RESTAURANT_DATA_SUCCESS',
    FETCH_RESTAURANT_DATA_FAILURE: 'FETCH_RESTAURANT_DATA_FAILURE',
    LOAD_MORE_RESTAURANT_DATA_START: 'LOAD_MORE_RESTAURANT_DATA_START',
    SET_ERROR_TO_NULL: 'SET_ERROR_TO_NULL',
    SET_SUCCESS_TO_NULL: 'SET_SUCCESS_TO_NULL'
};

export default RESTAURANT_ACTION_TYPES;
